# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [ ]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [187]:
import pandas as pd
import numpy as np
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [74]:
# read data
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data"
# \s+ one or more white space characters
data = pd.read_csv(url, sep = "\s+", parse_dates = [[0,1,2]])
data.tail()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [75]:
def fix(date):
    if date.year > 1978: # max year of this data sheet is 1978
        year = date.year - 100
    else:
        year = date.year
    # make a datetime format data
    
    d = datetime.date(year, date.month, date.day)
    return d
data["Yr_Mo_Dy"] = data["Yr_Mo_Dy"].apply(fix)
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [76]:
# dtype of Yr_Mo_Dy becomes object(datetime) after apply fix
# change Yr_Mo_Dy to datetime64[ns]
data["Yr_Mo_Dy"] = data["Yr_Mo_Dy"].astype("datetime64[ns]")

data.set_index("Yr_Mo_Dy", inplace = True)

In [77]:
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [79]:
# count how many values missing
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [82]:
# non-NA cells for each column
data.count()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

In [84]:
# solution 2, .notnull()
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [97]:
# total sum / non-NA cells number
tol_sum = data.sum().sum()
tol_count = data.count().sum()
wsp_mean = tol_sum/tol_count
print(wsp_mean)

10.227883764282181

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [102]:
# only include median, which is 0.5 of max in the form, default is [.25, .5, .75]
loc_stats = data.describe(percentiles = [.5,])
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [121]:
day_stats = pd.DataFrame(index = data.index)
day_stats["min"] = data.min(axis = 1)
day_stats["max"]  = data.max(axis = 1)
day_stats["mean"] = data.mean(axis = 1)
day_stats["standard_deviations"] = data.std(axis = 1)
day_stats

             min    max       mean  standard_deviations
Yr_Mo_Dy
1961-01-01  9.29  18.50  13.018182             2.808875
1961-01-02  6.50  17.54  11.336364             3.188994
1961-01-03  6.17  18.50  11.641818             3.681912
1961-01-04  1.79  11.75   6.619167             3.198126
1961-01-05  6.17  13.33  10.630000             2.445356
...          ...    ...        ...                  ...
1978-12-27  8.08  40.08  16.708333             7.868076
1978-12-28  5.00  41.46  15.150000             9.687857
1978-12-29  8.71  29.58  14.890000             5.756836
1978-12-30  9.13  28.79  15.367500             5.540437
1978-12-31  9.59  27.29  15.402500             5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [130]:
filt = data.index.month == 1
data.loc[filt].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [141]:
#option 1 resample
data.resample("Y").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-12-31,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-12-31,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [144]:
# option 2 groupby
data.groupby(by = [data.index.year]).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [147]:
data.resample("M").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-31,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02-28,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03-31,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04-30,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-31,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-31,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-30,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-31,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-30,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-31,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

In [153]:
## option 2, DatetimeIndex.to_period()
data.groupby(by = data.index.to_period("M")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [154]:
data.resample("W").mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

In [158]:
##groupby DatetimeIndex.to_period() option, displace of time is better
data.groupby(by = data.index.to_period("W")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [221]:
# convert Jan 2 1961 to datetime.date
d = datetime.date(1961, 1, 2)

# see which weekday Jan 2, 1961 is. it is 1, Monday
d.isoweekday()

# so week starts on Jan 2, 1961 means starts on Mon
# resample weekly starts on Mon, calculate min, max, mean, std
# Anchored offsets at: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#anchored-offsets
weekly = data.resample("W-MON").agg(["min", "max", "mean", "std"])

#grab first 52 DatetimeIndex
first_52w_idx = weekly.index[0:52]

# first 52 weeks of result
weekly.loc[first_52w_idx, :]

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1961-01-02  14.71  15.04  14.875000  0.233345  14.96  14.96  14.960000
1961-01-09  10.58  18.50  13.237143  2.596592   6.63  16.88  11.392857
1961-01-16   9.04  19.75  13.017143  3.858751   3.54  12.08   9.027143
1961-01-23   4.92  19.83  13.221429  5.349631   3.42  14.37   9.678571
1961-01-30  12.21  25.04  19.158333  5.499583  11.17  23.91  16.350000
1961-02-06  10.58  24.50  18.582857  5.499102   9.46  24.21  16.792857
1961-02-13  16.00  24.54  19.398571  3.198809  11.54  21.42  16.267143
1961-02-20   6.04  17.08  13.492857  4.032186  11.08  20.17  13.860000
1961-02-27   7.79  25.80  15.215714  7.024701   7.08  21.50  13.952857
1961-03-06   4.88  13.33  11.227143  2.931380   8.08  17.00  12.195714
1961-03-13   6.46  14.79  10.431667  3.036837   8.33  16.96  12.044286
1961-03-20   4.92  16.88  12.274286  3.902264   9.46  15.54  13.368571
1961-03-27   5.88  15.00   8.442857  3.306210   2.58  11.63   7.400000
1961-04-03   7.62  18.25  12.101429  4.777361   4.25  16.29   9.585714
1961-04-10   4.50  18.12  10.601429  4.860691   4.83  14.62  10.111429
1961-04-17   4.00  15.50   8.715714  4.221259   3.71  12.25   7.840000
1961-04-24   8.17  21.09  13.412857  4.548409   5.66  15.41  11.057143
1961-05-01   4.08  16.29  11.021429  4.840032   6.50  14.46  10.632857
1961-05-08   9.87  23.00  14.927143  5.108293  10.08  19.79  13.427143
1961-05-15   3.54  11.00   7.320000  2.738229   3.92  15.12   7.832857
1961-05-22   4.88  15.04   7.744286  3.639454   3.58  10.17   5.590000
1961-05-29   4.96  12.04   8.982857  2.935238   3.96  12.50   7.817143
1961-06-05   7.00  15.92  10.255714  3.061840   4.75  11.54   8.102857
1961-06-12   8.29  14.42  10.584286  2.305847   6.83   9.96   8.355714
1961-06-19   6.13  14.33  10.524286  3.036099   4.12  14.54   9.465714
1961-06-26   4.00  13.13   7.947143  2.944439   3.25  11.42   6.828571
1961-07-03   7.21  15.34  10.605000  3.148706   6.34  14.37   9.362857
1961-07-10   7.29  17.50  10.757143  3.428827   3.75  10.75   6.832857
1961-07-17   4.25  22.50  16.054286  6.419439   3.08  19.29  12.834286
1961-07-24   3.04   7.00   4.595714  1.490580   2.92   6.79   4.477143
1961-07-31   6.13  16.08  10.657143  4.068750   4.83  13.79   8.742857
1961-08-07   2.88  16.08  10.185714  4.134585   4.42  15.79   8.465714
1961-08-14   6.63  16.42  12.315000  3.351697   6.71  10.88   8.864286
1961-08-21  13.13  18.91  15.855714  2.473654   7.25  14.58  11.094286
1961-08-28   7.67  14.33  11.707143  2.366240   6.87  22.00  12.490000
1961-09-04   3.63  14.46   7.738571  3.904247   1.13  16.04   6.112857
1961-09-11   5.00  17.62  10.981429  4.961802   3.92  13.59   9.567143
1961-09-18   5.33  28.75  17.142857  7.698287   4.21  22.08  13.838571
1961-09-25   6.92  10.34   8.584286  1.379080   2.92  13.62   8.398571
1961-10-02  11.34  23.21  16.580000  3.958316   6.96  13.62  10.653333
1961-10-09   3.13  17.12  11.682857  5.958450   3.63  16.96   9.334286
1961-10-16   3.71  14.46  10.125000  3.867985   6.13  13.25   9.728571
1961-10-23  10.46  28.62  20.212857  7.330020   3.75  19.46  13.755714
1961-10-30   4.33  26.42  14.672857  8.168949   2.75  21.25  10.910000
1961-11-06   5.88  15.79  11.362857  3.564135   3.96  13.46   9.178571
1961-11-13   5.46  16.08  11.434286  4.099930   5.50  13.00   8.714286
1961-11-20   7.50  13.67  10.202857  2.096853   3.29  10.67   6.564286
1961-11-27   5.75  14.29   8.738571  3.149039   4.33  11.79   7.534286
1961-12-04   8.58  23.75  14.738571  6.403073   5.96  18.71  12.204286
1961-12-11  10.83  23.71  17.150000  4.638470   9.21  21.37  14.274286
1961-12-18   9.29  18.05  13.675714  3.059356   8.63  17.62  12.794286
1961-12-25  11.46  24.41  16.815714  4.856188   9.79  16.13  11.780000

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1961-01-02       NaN  10.83  13.17  ...  11.125000  2.057681  17.54  18.50
1961-01-09  3.613939   7.62  12.33  ...   8.412857  1.651027   5.46  16.62
1961-01-16  3.194035   7.08  19.50  ...   7.321429  4.029758   5.25  20.71
1961-01-23  3.790758   7.29  20.79  ...   8.958571  5.119787   6.50  15.92
1961-01-30  4.901779  10.92  25.84  ...  15.467143  3.872272  14.04  27.71
1961-02-06  5.174961   9.04  20.62  ...   9.817143  3.322493   9.17  26.38
1961-02-13  3.414873  13.67  21.34  ...  14.742857  1.925441  15.21  28.62
1961-02-20  3.186482   6.13  17.25  ...  12.757143  2.271811  14.09  29.63
1961-02-27  5.030022   6.08  22.42  ...  12.957143  4.867617   9.59  23.21
1961-03-06  3.375396   7.54  13.67  ...  11.287143  3.160679  10.21  23.45
1961-03-13  2.854896   8.00  16.38  ...  11.374286  2.785449  12.29  22.71
1961-03-20  2.515866   5.25  13.96  ...  11.960000  3.206795  11.29  22.79
1961-03-27  3.941755   4.79  15.63  ...  10.522857  2.760729   7.21  21.34
1961-04-03  4.071498   5.09  15.67  ...   9.322857  3.557802  10.71  18.63
1961-04-10  3.566966   8.25  18.29  ...   7.184286  2.401457   7.62  17.16
1961-04-17  2.856525   3.33  15.79  ...   6.071429  2.269474   5.75  16.17
1961-04-24  3.797344   6.04  17.00  ...  10.092857  2.456188   6.75  19.21
1961-05-01  3.113512   2.54  15.37  ...   6.452857  3.157730   5.13  18.63
1961-05-08  4.030586   8.42  21.21  ...  12.728571  4.220341   4.79  28.08
1961-05-15  4.113914   4.63  11.71  ...   6.155714  3.160991   6.54  11.12
1961-05-22  2.505410   5.33  15.96  ...   6.988571  2.297553   7.29  12.00
1961-05-29  2.996941   3.58  20.96  ...   8.488571  2.859105   6.13  14.33
1961-06-05  2.383567   6.83  12.25  ...   8.875714  1.858753   8.71  17.00
1961-06-12  1.174746   6.04  13.46  ...   7.812857  1.899629   5.37  13.25
1961-06-19  3.600860   6.50  15.50  ...  10.071429  3.591432   7.71  25.25
1961-06-26  2.996628   5.13  10.37  ...  11.238571  2.297023  10.83  19.08
1961-07-03  2.825312   7.71  12.17  ...  11.232857  2.905373   6.96  21.87
1961-07-10  2.287376   7.41  14.92  ...   8.755714  3.121591   5.04  15.34
1961-07-17  5.207328   5.46  14.29  ...  10.638571  2.385801   6.17  20.25
1961-07-24  1.302225   4.08  12.67  ...   5.655714  1.301420   4.21  10.13
1961-07-31  2.869325   6.67  15.67  ...   9.558571  4.247283   6.17  22.17
1961-08-07  4.268617   5.54  15.59  ...   8.975714  2.870249   7.92  18.54
1961-08-14  1.610899   6.00  11.63  ...   8.436667  2.926853   5.88  15.37
1961-08-21  2.951434   9.17  14.62  ...  12.607143  2.991314   9.59  21.92
1961-08-28  5.072961   9.50  17.83  ...  12.144286  3.644850   5.75  23.38
1961-09-04  4.891522   2.42  12.75  ...   7.328571  4.347031   4.79  24.71
1961-09-11  3.136855   3.63  14.88  ...   8.697143  2.631474   5.66  15.83
1961-09-18  6.302059   8.12  26.50  ...  13.774286  5.771808   7.21  23.91
1961-09-25  3.762886   5.33  12.17  ...   7.768571  3.285714   4.54  20.96
1961-10-02  2.875988   7.87  17.58  ...  11.714286  3.878908   7.58  21.37
1961-10-09  5.275038   4.96  20.96  ...   7.390000  4.018275   4.79  17.83
1961-10-16  2.700188   4.21  11.46  ...   9.881429  3.799427  12.46  20.46
1961-10-23  6.034633  10.37  22.63  ...  17.151429  5.685870  10.88  24.71
1961-10-30  6.770118   4.79  23.09  ...  12.120000  5.911153   8.50  27.29
1961-11-06  4.152334   4.83  14.33  ...  11.321429  3.121770  10.29  20.17
1961-11-13  2.735586   3.83  32.71  ...   7.261429  4.056519   6.13  11.12
1961-11-20  2.724591   6.46  26.63  ...   5.150000  2.889677   0.71   9.59
1961-11-27  3.025728   4.42  10.96  ...   8.977143  3.540841   5.50  20.46
1961-12-04  4.906560   8.00  19.92  ...   9.464286  3.861661   7.79  21.79
1961-12-11  4.055527   9.71  20.54  ...  12.438571  4.570188  10.71  22.83
1961-12-18  3.390157   8.08  16.66  ...   9.125714  4.356030   5.50  20.62
1961-12-25  2.311118   8.63  22.13  ...   8.505714  4.344824   5.29  17.67

                                   MAL
                 mean       std    min    max       mean       std
Yr_Mo_Dy
1961-01-02  18.020000  0.678823  13.83  15.04  14.435000  0.855599
1961-01-09  11.838571  3.770943  10.88  16.46  13.458571  1.945803
1961-01-16  11.125714  5.552215   5.17  16.92  10.120000  4.309625
1961-01-23  10.071429  3.932825   6.79  20.58  13.082857  5.269601
1961-01-30  21.514286  4.601144  17.50  27.63  22.340000  4.016300
1961-02-06  15.084286  6.159131   7.17  21.84  12.305714  5.106345
1961-02-13  22.152857  4.541596  17.04  21.09  18.845714  1.440565
1961-02-20  19.234286  5.241981  10.96  22.58  15.512857  4.719554
1961-02-27  17.005714  5.232262   6.67  23.87  15.090000  6.203754
1961-03-06  16.444286  5.041987   5.54  16.38  11.951667  3.988079
1961-03-13  18.057143  3.366000   8.75  22.54  16.325714  4.384913
1961-03-20  18.577143  4.223307  11.34  22.95  16.542857  4.627943
1961-03-27  13.025714  5.020946  13.13  22.50  17.312857  3.572360
1961-04-03  14.024286  3.396100   7.17  19.58  13.048571  4.197124
1961-04-10  11.218571  3.514064   7.21  15.34  11.638571  2.451377
1961-04-17   9.828571  3.548828   5.66  12.87   8.118571  2.534367
1961-04-24  13.595714  4.756903   4.96  20.46  12.642857  5.745835
1961-05-01  10.971429  4.482479   2.67  17.50   9.017143  5.191255
1961-05-08  17.552857  8.004173   3.83  26.58  16.740000  8.670898
1961-05-15   8.702857  1.839816   3.33  12.33   7.828571  3.543513
1961-05-22   9.850000  1.638180   5.91  14.96  10.970000  3.166544
1961-05-29  10.994286  2.858210   8.00  17.96  12.702857  4.448201
1961-06-05  12.960000  2.951226  10.63  15.71  12.787143  1.753166
1961-06-12   8.880000  3.063663   5.96  19.83  12.114286  4.936844
1961-06-19  16.155714  5.600226   6.13  24.71  15.817143  6.045593
1961-06-26  14.071429  2.806442  11.63  21.50  16.660000  3.774524
1961-07-03  15.904286  6.404261   8.50  21.29  13.743333  5.191060
1961-07-10  10.024286  3.518716   5.96  19.67  13.797143  4.462341
1961-07-17  13.681429  4.658295   9.13  21.96  12.977143  4.386649
1961-07-24   7.964286  2.041616   5.41  10.92   7.987143  2.263925
1961-07-31  12.401429  6.015719   9.25  25.37  14.267143  6.099319
1961-08-07  12.118571  4.395200   5.88  20.25  13.218571  5.196728
1961-08-14  11.725714  3.307234   6.83  15.16  10.833333  3.051869
1961-08-21  15.614286  4.557327  13.04  24.30  17.435714  4.180960
1961-08-28  16.328571  6.767278   8.29  20.62  15.700000  4.261346
1961-09-04  11.472857  7.505822   3.37  22.54   9.105714  6.302512
1961-09-11  11.915714  3.626720   5.79  20.25  12.648571  5.096127
1961-09-18  18.920000  6.299913   9.21  33.09  18.204286  7.226080
1961-09-25  12.870000  5.912343   5.25  16.21  10.814286  3.909467
1961-10-02  14.410000  5.651569   4.04  19.62  13.825714  5.194436
1961-10-09   8.947143  4.773041   4.83  16.25  10.440000  4.223482
1961-10-16  16.028571  3.546268  10.75  24.62  16.944286  5.206006
1961-10-23  17.864286  5.901237  13.46  33.45  23.695714  7.478050
1961-10-30  14.872857  6.493601   9.83  30.88  17.778571  7.917145
1961-11-06  15.655714  4.240487  13.37  23.58  18.178571  4.341065
1961-11-13   8.732857  2.062488   5.71  15.54  10.822857  3.662029
1961-11-20   5.655714  3.446766   2.00   8.71   5.088571  2.433389
1961-11-27  11.457143  5.738358   4.25  22.58  12.328571  6.846596
1961-12-04  13.791429  6.029509  11.17  21.29  16.630000  3.669600
1961-12-11  16.124286  4.894868   7.58  29.33  16.117143  7.294477
1961-12-18  12.684286  6.341117   5.91  21.12  12.868571  6.233125
1961-12-25  11.012857  4.825110   2.62  16.62   9.265714  5.308593

[52 rows x 48 columns]